# Upptime configuration for Zosia public endpoints
owner: epheterson
repo: upptime

sites:
  - name: Fact Check
    url: https://fact-check.info
  - name: Zosia Tools
    url: https://tools.zosia.io
  - name: Zosia Paste
    url: https://paste.zosia.io
  - name: Zosia Link Shortener
    url: https://at.zosia.io
  - name: Zosia API
    url: https://api.zosia.io/api

# No public status website - private monitoring only
# Results tracked in GitHub Issues

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
