# Upptime configuration for Zosia public endpoints
owner: epheterson
repo: upptime

sites:
  - name: Fact Check
    url: https://fact-check.info
  - name: Zosia Tools
    url: https://tools.zosia.io
  - name: Zosia Paste
    url: https://paste.zosia.io
  - name: Zosia Link Shortener
    url: https://at.zosia.io
  - name: Zosia API
    url: https://api.zosia.io/api

status-website:
  cname: health.zosia.io
  name: Zosia Status
  introTitle: "System Status"
  introMessage: Monitoring Zosia public services
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
